name: Build and test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.15.0
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Test
        run: npm test
